version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 2
  mysql:
    image: atanasminkov/mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: gatewayapp
      MYSQL_PASSWORD: gatewayapppw
      MYSQL_DATABASE: gateway_etl
  gateway-service:
    depends_on:
      - kafka
    image: atanasminkov/gateway-service:0.0.1-SNAPSHOT
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  cdc-service:
    depends_on:
      - kafka
    image: atanasminkov/gateway-cdc-service:0.0.1-SNAPSHOT
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GATEWAYAPP_DBHOST: mysql
