# let's simulate some environment variables
docker:
  host:
    ip: 10.200.10.1
gatewayapp:
  dbhost: ${docker.host.ip}
  dbport: 3306
  dbsuperuser: root
  dbsuperuserpassword: rootpassword
# end environment variables
spring:
  kafka:
    bootstrap-servers: ${docker.host.ip}:9092
